experiment:
  name: symbolic_forward_10000_phase2_parsimony_serious
  output_dir: reports/symbolic_regression/phase2

dataset:
  path: datasets/symbolic_regression/symbolic_forward_10000_phase2.parquet

training:
  max_train_samples: null
  max_test_samples: null
  seed: 123

features:
  source_columns:
    - phi_percent
    - C_percent
    - S_b_percent
    - sigma_b_inv
    - xi

  model_names:
    - phi
    - C
    - Sb
    - rb
    - xi

targets:
  - name: Vp # Vp Vs sigma sqrt_sigma
    source_column: Vp # Vp Vs sigma 
    transform: identity # identity or sqrt


pysr:
  niterations: 550 # [50,500]
  populations: 40 # [20,40]
  population_size: 30 
  maxsize: 30 # [15,35]
  parsimony: 0.01
  model_selection: best
  random_state: 123

  binary_operators:
    - "+"
    - "-"
    - "*"
    - "/"

  unary_operators:
    - "sqrt"
    - "square"
    - "log"
    - "exp"